### ISSUE TITLE
Use as a dev dependency

### ISSUE THREAD

**Issue by Foo42** [henhal/openapi-ts-backend#2]
First off, nice library, and excellent timing from my perspective.

At present the library contains methods for generating APIs at run time, or via a cli tool, as well as the types used by each of these. It would be nice if types used by the generated code (such as `RequestHandler`, `Request` etc) could be split out into a separate library, such that one could install `openapi-ts-backend` as a dev dependency to generate code, and install a slimmer, "types-only" library as a regular dependency to support the generated code at run time.

**Comment by henhal** [comment]
Thanks for the input @Foo42!
I'm not entirely sure I understand exactly what your use case is, so I would appreciate some more details. Do I understand correctly that you want to use only the code generation features, but not the `OpenApi` class itself? And you want to use those generated types for some other purpose than to implement operation handlers for use with `OpenApi.register()`?

I have indeed considered splitting up this into two modules (at least, I've also considered moving out the AWS Lambda stuff to an "add-on" and add other add-ons such as for Express, Hapi, ...), where the code generation could be generalized further to not only fit the types used by the `OpenApi` class but to serve a broader purpose. Is this what you're after, or did I misunderstand?

On the other hand, if you want to use `openapi-ts-backend` only to generate the utility types (on top of what `openapi-typescript` offers), wouldn't you then still only use those generated types in development, this being TypeScript after all? Most types-only modules are typically `devDependencies` anway, right? So when would you use 'a slimmer, "types-only" library' in _runtime_ - when this is just transpiled JavaScript? 

In the services I've implemented myself using this library, I've never added the generated types to source control, instead I've put the `gen` folder in `.gitignore` and run the code generator during development and from my build/deploy toolchain (the [example](https://github.com/henhal/openapi-ts-backend/blob/main/examples/example-app/serverless.yml#L29) uses serverless framework with a script hook to generate types just before packing the lambda function). I kind of suspect that what you want is to be able to use `openapi-ts-backend` during development to generate types, but then check those types into source control and use them when you don't have `depDependencies` (such as from other modules that don't want to rely on `openapi-ts-backend`)? Am I on the right track?

**Comment by Foo42** [comment]
It's quite possible my question doesn't make sense because I've not fully understood how the library works. I'm not sure it's as important to me as it seemed at the time.

I may have misunderstood, but the READMe appears to demonstrate two quite different uses of the library, the [simple hello world example](https://github.com/henhal/openapi-ts-backend#simple-hello-world-api-example) appears not to be making use of code gen, since the api spec is passed in at run-time. I presume in this usage there cannot be any compile time checking of the passed in operations object. In the [following example](https://github.com/henhal/openapi-ts-backend#generating-types-for-apis) however there is code gen performed, presumably, at pre-compile time. I'm interested in the latter style, using code gen to produce types to compile against. Since in this use case there is no need to load and interpret the spec at run time, my question was around whether this capability could be split out into a tool that could be installed as a dev dependency, used only as a pre-compile step, with the a slimmer library containing only the run time capabilities used by the generated code.

**Comment by henhal** [comment]
@Foo42 Sorry for not coming back earlier, but while I think most people would want to use the library as a dev dependency to generate types as part of their build step, and never put the generated code into source control, I decided to split the module up anyway to also accomodate for #4. So while this is not entirely finished yet, this means the types required to support the generated types are now in a separate `@openapi-ts/request-types` module. 

So if you do want to use this module to generate type files which are then put into source control or handed to some other party, they can be used without installing the entire openapi-ts-backend module for supporting types.

Does this help your usecase?

**Comment by henhal** [comment]
Fixed in #5 and https://github.com/henhal/openapi-types (https://www.npmjs.com/package/@openapi-ts/request-types)
