### ISSUE TITLE
I agree - great job. This is very useful library, but I have a probably noob question...

### ISSUE THREAD

**Issue by jimjoes** [henhal/openapi-ts-backend#7]
I'm want to define my handlers in separate files rather than all in the main app handler, but I can't figure out how to correctly type the methods in the separate files and hope someone can help? Might be useful to add this to the docs for relatively inexperienced typescripters like me?

let's say I have a getStatements.ts file like this:
```
    export const:any getStatements = (req:any, res:any, params: any):Promise<any> => {
        // Retrieve query parameters
        const {
            statementId,
            voidedStatementId,
        } = req.query;
        // TODO: implement business logic
    }
``` 

How do i import the correct types to replace the 'any's?

**Comment by elliots** [comment]
I think like this...
```typescript
const handler: OperationHandler<ExpressSource, 'getStatements'> = async (req, res, params) => {
        // Retrieve query parameters
        const {
            statementId,
            voidedStatementId,
        } = req.query;
        // TODO: implement business logic

}
```

**Comment by jimjoes** [comment]
Legend - thank you!

**Comment by henhal** [comment]
Sorry for the late reply - enjoyed an extended weekend. :) Thanks for helping out @elliots and hope you find it useful @jimjoes. 🙏 

Another approach is if you want to split your handlers in say two files, then you could use `Pick` to define the two subsets of handlers:

```
a.ts:
export const handlers: Pick<OperationHandlers<ExpressSource>, 'foo' | 'bar'> = {
  async foo(req, res) {
  },
  async bar(req, res) {
  }
};

b.ts
export const handlers: Pick<OperationHandlers<ExpressSource>, 'baz'> = {
  async baz(req, res) {
  }
};

main.ts:
import {handlers as a} from './a';
import {handlers as b} from './b';

const api = new OpenApi( ... ).register({
  definition: ' ... ',
  operations: { ... a, ... b },
  ...
});
```

**Comment by jimjoes** [comment]
Perfect - thanks :)
